var questions = [
  "What programming language was created and maintained by Sun Microsystems, now Oracle Corporation, in 1995?",
  "How many bits are in a byte?",
  "This common network protocol is used to transfer information via the World Wide Web",
  "This popular web-based programming language helps power web pages in addition to html and css elements.",
  "What device (firmware) found in computers is used to load the machine's operating system, thus booting it up?",
  "This essential software component is found on every computer, and handles task scheduling, application loading, and controlling settings/peripherals.",
  "A man by the name of _____ is credited as the creator of the first affordable, easy to use home PC.",
  "Many have dubbed ____ as the world's greatest hacker due to his successful efforts to hack into over 40 phone centers and computer databases in the late 1970s into the early 1980s.",
  "Who is the founder of Microsoft: a multimillion dollar tech company.",
  "The 'brain' of the computer system that handles processing is known as the ____",
  "What is the name of the system that utilizes 0's and 1's inside of computers to symbolize off and on as a method of coding?",
  "What university did Aaron attend?",
  "This technology company develops tax software utilized by ecommerce giants such as Amazon to ensure tax compliance.",
  "This computer manufacturing company has been in business since 1924, and has developed inventions such as the ATM and floppy disk.",
  "What year was the first apple computer, the Apple 1, first invented and built by Steve Wozniak and his friend Steve Jobs?",
  "Amazon developed a voice-controlled intelligent personal assistant (VCIPA) technology service, now found in many homes, named ___",
  "This $100+ billion-dollar company owns %95 percent of the search engine market.",
  "What computer data storage unit found in computers allows the CPU quick access and modification of stored data?",
  "1000 bytes is one ___",
  "What variable type in programming languages is typically used to store numbers?"
]
